name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download job postings
        run: ./download.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(+semver: patch) Automated download of job postings"
          file_pattern: "data/*"
  summarize:
    runs-on: ubuntu-latest
    needs:
      - download
    steps:
      - uses: actions/checkout@v2
      - name: Summarize job postings
        run: ./summarize.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(+semver: patch) Automated summarization of job postings"
          file_pattern: "data/*"
