name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Download job postings
        run: ./download.sh
      - run: |
          (
            git add data/ &&
              git commit -m "(+semver: patch) Automated download of job postings"
          ) || echo "Skipping because no changes were found"
      - name: Summarize job postings
        run: ./summarize.sh
      - run: |
          (
            git add data/ &&
              git commit -m "(+semver: patch) Automated summarization of job postings"
          ) || echo "Skipping because no changes were found"
      - run: |
          git push
