name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download job postings
        run: ./download.sh
      - name: Summarize job postings
        run: ./summarize.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(+semver: patch) Automated download and summarization"
          file_pattern: "data/*"
          status_options: "--untracked-files=yes"
